---
theme: Darmstadt
colortheme: orchid
outertheme: miniframes
fonttheme: structuresmallcapsserif 
title: Introduction à Python
subtitle:  2nde SNT
author: 'Rodrigo SCHWENCKE'
institute: 'Lycée PÉRIER of Marseille'
date: \today
# background-image: /home/luke/Documents/Images/AdminNSI.png
fontsize: 14pt
toc: false
slide_level: 1
navigation: horizontal
# logo: /home/luke/Images/perier.png
---