#!/bin/bash

# Author : Rodrigo SCHWENCKE & Valery BRUNIAUX

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

Author=""
PageSize="A4"
PageOrientation="Portrait"
TopMargin="0.75cm"
BottomMargin="1cm"
LeftMargin="1cm"
RightMargin="1cm"
FooterFont="Bell MT"
FooterSize="8"
StyleTemplate="$1"
StyleCss="$2"
Title=`echo $3 | cut -f1 -d'.'`

if [[ $# -lt 1 || $# -gt 3 ]]; then
		echo "============================================================="
		echo "==> md2all require 1, 2 or 3 arguments"
		echo "============================================================="
		echo "Usage with 1 argument : md2all markdownFile.md"
		echo "Example : md2all examples/proportionnalite.md"
		echo "============================================================="
		echo "Usage with 2 arguments : md2all cssFile.css markdownFile.md"
		echo "Example : md2all css/lesson.css examples/proportionnalite.md"
		echo "============================================================="
		echo "Usage with 3 arguments : md2all templateFile.template cssFile.css markdownFile.md"
		echo "1) Template file to apply"
		echo "2) Css file to apply"
		echo "3) Markdown file to convert"
		echo "Example : md2all templates/lesson.template css/lesson.css examples/proportionnalite.md"
		echo "============================================================="
		exit 1
fi

if [ $# -eq 1 ]; then
	Title=`echo $1 | cut -f1 -d'.'`
	StyleTemplate="$HOME/.config/md2all/templates/default.template"
	StyleCss="$HOME/.config/md2all/css/default.css"
	GraphvizFilter="$HOME/.config/md2all/graphviz/default.py"
	HighlightStyle="$HOME/.config/md2all/css/massilia.theme"
	echo "============================================================="
	echo "=> You invoque md2all with default template and css files"
	echo "============================================================="
fi

if [ $# -eq 2 ]; then
	StyleCss="$1"
	Title=`echo $2 | cut -f1 -d'.'`
	StyleTemplate="$HOME/.config/md2all/templates/default.template"
	echo "============================================================="
	echo "=> You invoque md2all with default template file"
	echo "============================================================="
fi

echo "============================================================="
echo "=> Processing Markdown file : "$Title".md"
echo "=> Make HTML file : $Title.html"
echo "=> With Template file : $StyleTemplate"
echo "=> And CSS file : $StyleCss"
echo "============================================================="

#INITIAL MD2HTML CODE:
# pandoc "$Title".md --from=markdown+emoji --to=html5 --self-contained --highlight-style=tango --template="$StyleTemplate" -c "$StyleCss" --number-sections --standalone --webtex="http://latex.codecogs.com/svg.latex?" -o "$Title".html

# pandoc "$Title".md --from=markdown+emoji --to=html5 --self-contained --highlight-style="$HighlightStyle" --filter "$GraphvizFilter" --filter pandoc-pyplot --filter pandoc-plantuml --template="$StyleTemplate" -c "$StyleCss" --number-sections --standalone --webtex="http://latex.codecogs.com/svg.latex?" -o "$Title".html
pandoc -s --mathjax -c "$StyleCss" --from=markdown+emoji --to=html5 --template="$StyleTemplate" --highlight-style="$HighlightStyle" --filter "$GraphvizFilter" --filter pandoc-pyplot --filter pandoc-plantuml --number-sections < "$Title".md -o "$Title".html

echo "============================================================="
echo "=> Make PDF file : $Title.pdf ..."
echo "============================================================="

Author=$(head -2 "$Title".md | tail -1)
Author=${Author:2}

# INITIAL MD2HTML CODE:
#wkhtmltopdf --encoding 'utf-8' --print-media-type --footer-line --footer-spacing 2 --footer-font-name "$FooterFont" --footer-font-size "$FooterSize" --footer-left "$Author" --footer-right "[page] / [topage]" --margin-top "$TopMargin" --margin-left "$LeftMargin" --margin-right "$RightMargin" --margin-bottom "$BottomMargin" -O "$PageOrientation" -s "$PageSize" --javascript-delay 500 --no-stop-slow-scripts "$Title".html "$Title".pdf

# MY CODE:
wkhtmltopdf --encoding 'utf-8' --print-media-type --footer-line --footer-spacing 2 --footer-font-name "$FooterFont" --footer-font-size "$FooterSize" --footer-left "$Author" --footer-right "[page] / [topage]" --margin-top "$TopMargin" --margin-left "$LeftMargin" --margin-right "$RightMargin" --margin-bottom "$BottomMargin" -O "$PageOrientation" -s "$PageSize" --debug-javascript --enable-javascript --javascript-delay 1000 --no-stop-slow-scripts "$Title".html "$Title".pdf
