#!/bin/bash
. /usr/lib/md2all.lib

# md2all is initially inspired by the work of Valery BRUNIAUX (https://github.com/ValeryBruniaux/md2htmlpdf)
# Author : Rodrigo SCHWENCKE

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

Author=""
PageSize="A4"
PageOrientation="Portrait"
TopMargin="0.75cm"
BottomMargin="1cm"
LeftMargin="1cm"
RightMargin="1cm"
FooterFont="Bell MT"
FooterSize="8"

# Code Layout, EXCEPT COLORS
CodeLayoutCss="$HOME/.config/md2all/css/massilia.css"
# Code COLORS (name coherent with pandoc options)
HighlightStyle="$HOME/.config/md2all/css/massiliaDark.theme"
# For Shortcut purposes,possible values: light, dark, or dual
CodeStyle="dual"
PageStyleCss="$HOME/.config/md2all/css/lesson.css"
GraphvizFilter="$HOME/.config/md2all/filters/graphviz/graphviz.py"
PlantUMLFilter="$HOME/.config/md2all/filters/plantuml/plantuml.py"
Template="$HOME/.config/md2all/templates/lesson.template"
JsStyle="$HOME/.config/md2all/js/script.js"

LastElemInCodeLayoutCss=`echo $CodeLayoutCss | rev | cut -d'/' -f 1 | rev`
CodeLayoutCssName=`echo $LastElemInCodeLayoutCss | cut -f1 -d'.'`

splitOptionsAndFilename $*
checkSyntax $filename
Title=`echo $filename | cut -f1 -d'.'`

echo "=> Processing from Markdown file : "$Title".md"
echo "=> Make HTML file : "$Title".html"
# echo "=> with Highlight Style : $HighlightStyle"
# echo "=> with Code Style : $CodeStyle"
# echo "=> with Page Style CSS : $PageStyleCss"
# echo "=> with Template : $Template"

detectIfDualExport

exportToHTML

echo "=> Make PDF file : $Title.pdf ..."

Author=$(head -2 "$Title".md | tail -1)
Author=${Author:2}

exportToPDF
