---
# aspectratio: 169
theme: Darmstadt
colortheme: orchid
# outertheme: miniframes
outertheme: smoothbars
fonttheme: structuresmallcapsserif
# themeoptions : (a list)
title: Introduction à Python
thanks: OpenClassRooms
subtitle:  1ère NSI
author: 'Rodrigo SCHWENCKE'
institute: 'Lycée PÉRIER of Marseille'
date: \today
# background-image: /home/luke/Images/AdminNSI.png
fontsize: 8pt
# mainfont: arial
# toc: true
# section-titles: true
navigation: horizontal
header-includes:
- |
  ```{=latex}
  %\usepackage[utf8]{inputenc}
  %\usepackage{fontenc}
  %\usepackage[french]{babel}
  %\usepackage{bookman}
  \usepackage{url}
  \usepackage{multicol}       % ATTENTION : PAS de 's', PAS 'multicols'

  % MATHS
  \usepackage{amsthm}
  \setbeamertemplate{theorems}[numbered]
  \newtheorem{defi}{Définition}[]
  \newtheorem{thm}{Théorème}[]
  \newtheorem{prop}{Proposition}[]
  \newtheorem{pte}{Propriété}[]
  \newtheorem{cons}{Conséquence}[]
  \newtheorem{idee}{Idée}[]
  \newtheorem{rem}{Remarque}[]

  \logo{\includegraphics[height=1.5cm]{img/chouette.png}}
  %\titlegraphic{\includegraphics[height=1.5cm]{/home/luke/Images/AdminNSI.png}}
  
  %TABLE OF CONTENTS (TOC) - AUTONUMBERING FORMAT
  \defbeamertemplate*{section in toc}{sections numbered roman}{%
  \leavevmode%
  \MakeUppercase{\romannumeral\inserttocsectionnumber}.\ %
  \inserttocsection\par}
  \setbeamertemplate{section in toc}[sections numbered roman]
  \makeatletter
  \setbeamertemplate{subsection in toc}{\leavevmode\normalsize\usebeamerfont{subsection in toc}\leftskip=2.4em\usebeamerfont{subsection in toc}\rlap{\hskip-1.2em\inserttocsubsectionnumber. }\inserttocsubsection\par}
  \setbeamertemplate{subsubsection in toc}{\leavevmode\normalsize\usebeamerfont{subsubsection in toc}\leftskip=4.2em\usebeamerfont{subsubsection in toc}%
  \rlap{\hskip-1.2em\@alph\inserttocsubsubsectionnumber. }\inserttocsubsubsection\par}
  \makeatother

  %TABLE OF CONTENTS - TOC - Sommaire
  \AtBeginSection[]
  {
  \begin{frame}<beamer>{LE PLAN}
  \tableofcontents[currentsection,currentsubsection, 
      hideothersubsections, 
      sectionstyle=show/shaded,
  ]
  \end{frame}
  }

  %FOOTNOTES
  \setbeameroption{show notes}
  \setbeamertemplate{note page}[]

  %===================================================================================================
  % HEADLINE TEMPLATE & AUTONUMBERING (beamerouterthememiniframes.sty modified)
  %\addtobeamertemplate{headline}{}
  %{
  %  \leavevmode%
  %  \hbox{%
  %  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,left]{section in head/foot}%
  %   \MakeUppercase{\romannumeral\insertsectionnumber}.\ %
  %    %\insertsection \usebeamerfont{section in head/foot} \insertsectionhead\hspace*{2ex}
  %  \end{beamercolorbox}%
  %  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,left]{subsection in head/foot}%
  %    \usebeamerfont{subsection in head/foot}\thesubsection)\ \insertsubsectionhead\hspace*{2ex}
  %  \end{beamercolorbox}%
  %  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,left]{subsubsection in head/foot}%
  %    \usebeamerfont{subsubsection in head/foot}\thesubsubsection)\ \insertsubsubsection\hspace*{2ex}
  %  \end{beamercolorbox}%
  %  }%
  %  \vskip0pt%
  %}

  \makeatletter
  % Comprime la zone miniframe en une ligne. Komprimiert die miniframe Kreise auf eine Linie
  \beamer@compresstrue
  \makeatother
  
  % Bleu Marine
  \definecolor{bleuMarine}{HTML}{1B4B80}

  % Bleu Moyen
  \definecolor{bleuMoyen}{HTML}{0C649E}

  % Bleu Clair
  \definecolor{bleuClair}{HTML}{2CA0EF}

  % Farbe der Elemente der headline
  \setbeamercolor{section in head/foot}{fg = red, bg = bleuMarine!100}
  \setbeamercolor{subsection in head/foot}{fg = green, bg = bleuMoyen!100}

  % HEADLINE TEMPLATE
  \setbeamertemplate{headline}
  {
  \leavevmode%
  \hbox{%
  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,left]{section in head/foot}%
   \MakeUppercase{\romannumeral\insertsectionnumber}.\ %
    \insertsection \usebeamerfont{section in head/foot} \insertsectionhead\hspace*{2ex}
  \end{beamercolorbox}%
  }%
  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,left]{subsection in head/foot}%
    \usebeamerfont{subsection in head/foot}\thesubsection)\ \insertsubsectionhead\hspace*{2ex}
  \end{beamercolorbox}%
  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,left]{subsubsection in head/foot}%
    \usebeamerfont{subsubsection in head/foot}\thesubsubsection)\ \insertsubsubsection\hspace*{2ex}
  \end{beamercolorbox}%
  \vskip0pt%
  }

  % FRAMETITLE DEFINITION
  \setbeamertemplate{frametitle}
  {
  %\vskip-24pt % to shift up the frametitle
  \hbox{ 
   \begin{beamercolorbox}[wd=.0675\textwidth]{} % left shift
   \end{beamercolorbox} 
   \begin{beamercolorbox}[sep=4pt]{section in head/foot}
   \insertframetitle
   \end{beamercolorbox}
   }
  }


  %pour customiser le title et/ou le body des block système Beamer: normal, ou 'alerted', ou 'example'
  %\setbeamercolor{block title alerted}{fg=black!90,bg=brown!60!yellow}
  %\setbeamercolor{block body alerted}{fg=black!90,bg=brown!60!yellow}
  \definecolor{lightCodeBackground}{HTML}{F5F2F0}
  \definecolor{languageTitle}{HTML}{3593FF}

  %CUSTOMIZE ENUMERATE SYMBOLS
  %replace circle by: default, circle, square, ou ball IF option numerostyle is NOT used
  %pour les items de 1er niveau:
  %\setbeamertemplate{enumerate item}[circle]
  %pour les items de 2ème niveau:
  %\setbeamertemplate{enumerate subitem}[circle]

  %ADD PAGE AUTO NUMBERING TO NAVIGATION SYMBOLS : (Bottom Right)
  \addtobeamertemplate{navigation symbols}{}{ 
    \usebeamerfont{footline}\usebeamercolor[bg]{title}%
    \hspace{1.5em}Page \insertframenumber / \inserttotalframenumber
  }

  \newenvironment<>{lightCode}[1]{%
    \begin{actionenv}#2%
        \def\insertblocktitle{#1}%
        \par%
        \mode<presentation>{%
         \setbeamercolor{block title}{use=structure,fg=white,bg=languageTitle!100}
         \setbeamercolor{block body}{use=structure,fg=black,bg=lightCodeBackground!50}
         %\setbeamercolor{itemize item}{fg=orange!20!black}
         %\setbeamertemplate{itemize item}[triangle]
       }%
        \usebeamertemplate{block begin}}%
      {\par\usebeamertemplate{block end}\end{actionenv}}

  %\newenvironment<>{lightCode}[1]{%
  %  \begin{actionenv}#2%
  %      \def\insertblocktitle{#1}%
  %      \par%
  %      \mode<presentation>{%
  %       \setbeamercolor{block title}{fg=white,bg=languageTitle!100}
  %       %\setbeamercolor{block body}{fg=black,bg=lightCodeBackground!50}
  %       %\setbeamercolor{itemize item}{fg=orange!20!black}
  %       %\setbeamertemplate{itemize item}[triangle]
  %     }%
  %      \usebeamertemplate{block begin}}
  %    {\par\usebeamertemplate{block end}\end{actionenv}}
  ```
---
